### ISSUE TITLE
yarn error on install (Debian unstable)

### ISSUE THREAD

**Issue by buoncri** [long2ice/restful-admin#1]
As in read.me, going to Run local i made:

    git clone https://github.com/long2ice/restful-admin.git (and move to that dir)
    cp .env.example .env and update
    yarn && yarn serve.

the last line (yarn) return 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

    yarn --version
    0.32+git
    node -v
    v12.18.1
    uname -a
    Linux idefix 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux

After googoling the error i found that i have a wrong yarn, so i install from 
    https://classic.yarnpkg.com/en/docs/install/#debian-stable

After that the frontend compile and go :-D

**Comment by long2ice** [comment]
Update yarn version first
