### ISSUE TITLE
hi，建议更新如下的地方

### ISSUE THREAD

**Issue by liuqlive** [long2ice/restful-admin#6]
hi，建议在CustomTable.vue微调一下，可以解决如下的问题：
1）确保js.XLSX获取的日期数据正确
2) 保证 空字符 可以正确处理

select_file(file) {
      let reader = new FileReader();
      let that = this;
      reader.onload = function (e) {
        let data = new Uint8Array(e.target.result);
        // 配置 cellDates: true，保证 日期/时间类型正确传输到服务器端
        let workbook = XLSX.read(data, {type: 'array',cellDates: true});
        let sheet_name = workbook.SheetNames[0];
        let sheet = workbook.Sheets[sheet_name];
        // 按照源码来定义第二个参数，给defval赋值为空的字符串
        const sheet2JSONOpts = {
          /** Default value for null/undefined values */
          defval: ''//给defval赋值为空的字符串
        }
        let json_data = XLSX.utils.sheet_to_json(sheet,sheet2JSONOpts);//
        that.$http.post(that.uri + '/import', json_data).then(res => {
          that.$refs.table.refresh();
          that.$snotify.success(this.$t("messages.import", res.data));
        })
      };
      reader.readAsArrayBuffer(file);
    },

**Comment by long2ice** [comment]
Hi，由于我本人不是搞前端的，本项目也是fork自另一个项目然后做了一些更改。你说的地方我会优化一下，有兴趣的话可以一起完善这个项目。

**Comment by liuqlive** [comment]
有可以持续优化的地方，我在这里告诉你。
