### ISSUE TITLE
yarn && yarn serve

### ISSUE THREAD

**Issue by littleforce163** [long2ice/restful-admin#7]
$ yarn && yarn serve
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.46s.
yarn run v1.22.4
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/2 modules 0 activeevents.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch 
.........

**Comment by long2ice** [comment]
see https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached
